---
- name: Ensure Tracer package is installed
  ansible.builtin.dnf:
    name: tracer
    state: present

- name: Update packages
  ansible.builtin.dnf:
    name: "*"
    state: "{{ 'latest' }}"  # Yes, redundant, but necessary to not anger the lint gods...
    update_cache: true

- name: Check if system reboot is needed
  ansible.builtin.command: tracer
  ignore_errors: true
  register: reboot_check
  changed_when: _reboot_check.stdout.find('reboot') != -1 or reboot_forced
  failed_when: reboot_check.stdout.find('unsupported') != -1
  when: reboot_enabled or reboot_forced
  notify: Reboot system
