---
- hosts: all
  any_errors_fatal: true
  become: true
  name: Update operating system

  vars:
    reboot_enabled: true
    reboot_msg: "System is going down to apply updates."
    reboot_timeout: 600
    reboot_forced: false

  handlers:
    - name: Reboot system
      ansible.builtin.reboot:
        msg: "{{ reboot_msg }}"
        reboot_timeout: "{{ reboot_timeout }}"
      when: reboot_enabled or reboot_forced

  tasks:
    - name: Include appropriate package manager tasks
      ansible.builtin.include_tasks: "../tasks/{{ ansible_pkg_mgr }}.yml"
